from __future__ import annotations

from uuid import UUID

from app.models.schemas import IncidentReport, InvestigationReport, PostmortemReport, RemediationStep


class PostmortemService:
    def generate(self, report: InvestigationReport | IncidentReport) -> PostmortemReport:
        if isinstance(report, IncidentReport):
            title = report.incident.title
            investigation_id = report.investigation_id
            status = report.status.value
            owners = [action.owner for action in report.recommended_actions]
            impact = f"{report.incident.domain.value} incident assessed as {status} at risk {report.risk_score}/100."
            root = self._root_cause_from_findings(report.findings)
            timeline = report.timeline
            actions = report.recommended_actions
        else:
            title = report.alert.title
            investigation_id = report.investigation_id
            owners = [action.owner for action in report.recommended_actions]
            impact = f"Security investigation assessed as {report.verdict.value} at risk {report.risk_score}/100."
            root = self._root_cause_from_findings(report.findings)
            timeline = report.timeline
            actions = report.recommended_actions

        contributing = [
            finding.summary for finding in report.findings[:4] if finding.summary
        ] or ["Insufficient evidence captured for contributing factors."]
        return PostmortemReport(
            investigation_id=UUID(str(investigation_id)),
            title=f"Postmortem: {title}",
            summary=report.executive_summary,
            impact=impact,
            timeline=timeline,
            root_cause_hypothesis=root,
            contributing_factors=contributing,
            corrective_actions=actions
            or [
                RemediationStep(
                    priority=1,
                    action="Assign an owner to complete root cause validation.",
                    owner="Incident Commander",
                    rationale="No corrective actions were generated by the investigation workflow.",
                )
            ],
            owners=sorted(set(owners)) or ["Incident Commander"],
        )

    @staticmethod
    def _root_cause_from_findings(findings) -> str:
        if not findings:
            return "Root cause requires follow-up analysis."
        return findings[-1].summary
