apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enterprise-rag-vectorstore
  namespace: enterprise-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enterprise-rag-logs
  namespace: enterprise-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
